name: Release

on:
  push:
    tags:
      - v*

jobs:
  TestPyPi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: TestPyPi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv build
      - run: uv publish --index testpypi --trusted-publishing always

  InstallLibrary:
    name: Install from TestPyPI
    needs: [TestPyPi]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv run --with cloud-autopkg-runner --no-project -- python -c "import cloud-autopkg-runner"
