name: Release Dev to TestPyPI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  publish-to-testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: TestPyPI
      url: https://test.pypi.org/p/cloud-autopkg-runner
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Bump Version
        run: uv version $(uv version --short).${{ github.run_number }}

      - name: Publish
        run: uv publish --index testpypi --trusted-publishing always


  install-library-from-testpypi:
    name: Test Installation from TestPyPI
    needs: [publish-to-testpypi]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install
        run: uv run --with cloud-autopkg-runner --extra-index-url https://test.pypi.org/simple/ --index-strategy unsafe-best-match --no-project -- python -c "import cloud_autopkg_runner"
